# Generated by Django 5.2.8 on 2025-11-14 23:44

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('NEEDS_APPROVAL', 'Needs Approval'), ('STALLED', 'Stalled'), ('ABANDONED', 'Abandoned'), ('DEFINING_SCOPE', 'Defining Scope'), ('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed')], default='DEFINING_SCOPE', max_length=20, verbose_name='Status')),
                ('difficulty', models.CharField(choices=[('VERY_EASY', 'Very Easy'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('VERY_HARD', 'Very Hard')], default='MEDIUM', max_length=15, verbose_name='Difficulty')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=15, verbose_name='Priority')),
                ('start_date', models.DateField(default=projects.models.get_default_start_date, verbose_name='Start Date')),
                ('end_date', models.DateField(default=projects.models.get_default_end_date, verbose_name='End Date')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organisations.team')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_components', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_components', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visiblity', models.CharField(choices=[('HIDDEN', 'Hidden'), ('VISIBLE', 'VISIBLE'), ('TEAM_ONLY', 'Team Only')], default='TEAM_ONLY', max_length=20, verbose_name='Visibility')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done')], default='TO_DO', max_length=20, verbose_name='Status')),
                ('difficulty', models.CharField(choices=[('VERY_EASY', 'Very Easy'), ('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('VERY_HARD', 'Very Hard')], default='MEDIUM', max_length=15, verbose_name='Difficulty')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=15, verbose_name='Priority')),
                ('start_date', models.DateField(default=projects.models.get_default_start_date, verbose_name='Start Date')),
                ('due_date', models.DateField(default=projects.models.get_default_end_date, verbose_name='End Date')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.component')),
            ],
        ),
    ]
