# Generated by Django 5.2.9 on 2026-02-03 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmembership_invite_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(help_text='The super-admin of the project.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('complete', 'Complete'), ('archived', 'Archived')], default='pending', help_text='Controls the visibility and editability of the project.', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='invite_email',
            field=models.EmailField(blank=True, help_text='For sending invites to non-registered users.', max_length=254, null=True),
        ),
    ]
