# Generated by Django 5.2.9 on 2026-02-03 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(help_text='The user who performed the action. If Null, implies a System event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_invite', 'Project Invitation'), ('invite_accepted', 'Invitation Accepted'), ('invite_rejected', 'Invitation Rejected'), ('project_completed', 'Project Completed'), ('task_overdue', 'Task Overdue'), ('removed', 'Removed from Project')], help_text='Determines the icon and frontend routing logic.', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='The user who will see this notification in their dashboard.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
