from django.contrib.auth import get_user_model
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from apps.notifications.models import Notification

User = get_user_model()

class NotificationAPITest(APITestCase):

    def setUp(self):
        # 1. Create two users
        self.user_a = User.objects.create_user(username='user_a', password='password')
        self.user_b = User.objects.create_user(username='user_b', password='password')

        # 2. Create notifications for User A
        self.notif_a = Notification.objects.create(
            recipient=self.user_a,
            notification_type='task_overdue',
            message="User A's Task"
        )

        # 3. Create notifications for User B (to test privacy)
        self.notif_b = Notification.objects.create(
            recipient=self.user_b,
            notification_type='task_overdue',
            message="User B's Task"
        )

        # 4. Authenticate as User A by default
        self.client.force_authenticate(user=self.user_a)

    def test_list_notifications_authenticated(self):
        """
        Happy Path: User A should see their own notifications.
        """
        # The URL name comes from router.register(..., basename='notification')
        url = reverse('notification-list') 
        response = self.client.get(url)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        
        # Check that we got results
        results = response.data.get('results', response.data)
        
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]['message'], "User A's Task")

    def test_list_notifications_privacy(self):
        """
        Privacy: User A should NOT see User B's notifications.
        """
        url = reverse('notification-list')
        response = self.client.get(url)
        results = response.data.get('results', response.data)

        # Ensure User B's message is NOT in the list
        messages = [n['message'] for n in results]
        self.assertNotIn("User B's Task", messages)

    def test_mark_read_action(self):
        """
        Action: User A can mark their own notification as read.
        """
        # 'notification-mark-read' is the URL name generated by the @action(detail=True) in the viewset
        url = reverse('notification-mark-read', kwargs={'pk': self.notif_a.id})
        
        response = self.client.post(url)
        
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        
        # Verify in Database
        self.notif_a.refresh_from_db()
        self.assertTrue(self.notif_a.is_read)

    def test_mark_read_unauthorized(self):
        """
        Security: User A tries to mark User B's notification as read.
        Should return 404 (Not Found) because the queryset filters it out.
        """
        url = reverse('notification-mark-read', kwargs={'pk': self.notif_b.id})
        
        response = self.client.post(url)
        
        # It's usually 404 because your get_queryset() filters by request.user
        # So User B's ID effectively "doesn't exist" for User A.
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_unauthenticated_access(self):
        """
        Security: Anonymous user tries to access API.
        """
        self.client.force_authenticate(user=None) # Logout
        
        url = reverse('notification-list')
        response = self.client.get(url)
        
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)