# Generated by Django 5.2.8 on 2025-11-15 00:33

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=50, verbose_name='Theme Name')),
                ('primary_color', models.IntegerField(default=100, verbose_name='Primary Color')),
                ('secondary_color', models.IntegerField(default=100, verbose_name='Secondary Color')),
                ('tertiary_color', models.IntegerField(default=100, verbose_name='Tertiary Color')),
                ('text_color', models.IntegerField(default=100, verbose_name='Text Color')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('theme_mode', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10, verbose_name='Theme Mode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(default=users.models.get_default_theme, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.theme')),
            ],
        ),
    ]
