# Generated by Django 5.2.8 on 2025-11-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('LEADER', 'Leader')], default='MEMBER', max_length=10, verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organisation Name')),
                ('org_type', models.CharField(choices=[('PERSONAL', 'personal'), ('TEAM', 'team')], default='PERSONAL', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='Organisation Logo')),
                ('super_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_members_count', models.IntegerField(default=1, verbose_name='Minumum Team Size')),
                ('max_members_count', models.IntegerField(default=10, verbose_name='Maximum Team Size')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('department', models.CharField(choices=[('STANDARD', 'standard'), ('SALES', 'sales'), ('SERVICE', 'service'), ('MARKETING', 'marketing')], default='STANDARD', max_length=20, verbose_name='Department')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private')),
                ('enrollment_type', models.CharField(choices=[('ADMIN', 'admin'), ('MEMBER', 'member'), ('REQUEST', 'request'), ('OPEN', 'open')], default='REQUEST', max_length=15, verbose_name='Enrollment Type')),
                ('members', models.ManyToManyField(related_name='teams', through='organisations.Membership', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organisations.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='organisations.team'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'team')},
        ),
    ]
