# Generated by Django 5.2.8 on 2025-11-15 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('STARRED', 'Starred')], default='UNREAD', max_length=15, verbose_name='Status')),
                ('type', models.CharField(choices=[('MENTION', 'Mention'), ('ASSIGNMENT', 'Assignment'), ('OVERDUE', 'Overdue')], max_length=25, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_to', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
