# Generated by Django 5.2.9 on 2026-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
