# Generated by Django 5.2.9 on 2026-02-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_owner_alter_project_status_and_more'),
        ('tasks', '0002_task_overdue_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='overdue_notified',
            field=models.BooleanField(default=False, help_text='System field to track if the assignee has been alerted of a late deadline.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='The project this task is grouped under.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
    ]
