export * from './register-page';
export * from './login-page';
export * from './home-page';
export * from './reset-password-page';
export * from './confirm-password-reset-page'
export * from './settings-page';
export * from './project-workspace-page';
export * from './about-page';
export * from './contact-page';
export * from './sitemap-page';
export * from './not-found-page';