# Generated by Django 5.2.9 on 2026-02-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projects', '0005_alter_project_owner_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='project',
            field=models.ForeignKey(help_text='The project this message belongs to (acts as the chat room).', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='projects.project'),
        ),
    ]
