"""
URL Configuration for the Projects App.

This module defines the routing for Project resources and their associated 
comments using DRF's DefaultRouter.

Exposed Endpoints:
    - GET /api/projects/            -> List all projects (filterable).
    - POST /api/projects/           -> Create a new project.
    - GET /api/projects/<id>/       -> Retrieve project details.
    - POST /api/projects/<id>/pin/  -> Custom action to Pin/Unpin a project.
    
    - GET /api/projects/comments/   -> List comments (usually filtered by ?project=ID).
    - POST /api/projects/comments/  -> Add a comment to a project.
"""

from django.urls import path, include
from .views import ProjectViewSet, ProjectChatViewSet
from rest_framework.routers import DefaultRouter

# Initialize the router to auto-generate standard CRUD URLs
router = DefaultRouter()

# 1. Main Project Resource
# Registers the ViewSet at the root of this app's namespace (e.g., /api/projects/)
router.register(r'', viewset=ProjectViewSet, basename="project")

# 2. Project Comments
# Registers the comments at a sub-path (e.g., /api/projects/comments/)
# Note: While nested routers exist, registering this separately is a simpler 
# approach for an MVP, relying on query params (e.g., ?project=1) to filter.
# This wasnt even really needed in the end. Moved to a more complex chat app. Keeping this here to satisify DB migrations.
router.register(r'comments', viewset=ProjectChatViewSet, basename="project_comment")

urlpatterns = [
    # Include all the routes generated by the router
    path('', include(router.urls))
]